version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/:/app/client
    ports:
      - 3000:3000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/:/app/server
    ports:
      - 5000:5000